=== YangZi520/dataTransfer/config/transfer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://www.pccw.com"
			xmlns="http://www.pccw.com">
			
	<xsd:annotation>
		<xsd:appinfo>etl tool schema</xsd:appinfo>
		<xsd:documentation></xsd:documentation>
	</xsd:annotation>
			
	<!-- 简易元素定义  -->
	<xsd:element name="dbName" type="xsd:string"/>
	<xsd:element name="table" type="xsd:string"/>
	<xsd:element name="engine" type="xsd:string"/>
	<xsd:element name="sql" type="xsd:string"/>
	<xsd:element name="params" type="xsd:string"/>
	
	
	<!-- 元素分组定义 -->
	<xsd:group name="srcSqlGroup">
		<xsd:sequence>
			<xsd:element ref="sql"/>
			<xsd:element ref="params" minOccurs="0"/>
		</xsd:sequence>
	</xsd:group>
	
	<xsd:group name="srcOptionGroup">
		<xsd:choice>
			<xsd:element ref="table"/>
			<xsd:group ref="srcSqlGroup" />
		</xsd:choice>
	</xsd:group>
	<!-- 复合元素定义 -->
	<xsd:element name="srcInfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dbName"/>
				<xsd:group ref="srcOptionGroup" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="targetInfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dbName"/>
				<xsd:element ref="table"/>
				<xsd:element ref="engine" minOccurs="0"/>
				<xsd:element ref="sql" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="transferInfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="srcInfo" />
				<xsd:element ref="targetInfo"/>
			</xsd:sequence>
			<xsd:attribute name="backup" type="xsd:boolean" default="false"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="item">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dbName" />
				<xsd:element ref="sql" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="callBackInfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="item"  maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- 根元素 -->
	<xsd:element name="root">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="transferInfo" maxOccurs="unbounded" />
				<xsd:element ref="callBackInfo" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== YangZi520/dataTransfer/config/transfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.pccw.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pccw.com transfer.xsd">
	<transferInfo backup="false">
		<srcInfo>
			<dbName>ppmpcs2</dbName>
			<sql>
				<![CDATA[
					select u.user_id, u.account, u.user_name from arch_user u 
			    ]]>
			</sql>
		</srcInfo>
		<targetInfo>
			<dbName>form</dbName>
			<table>my_test</table>
			<sql>create index my_test_idx on my_test (user_id)</sql>
		</targetInfo>
	</transferInfo>
	<transferInfo backup="false">
		<srcInfo>
			<dbName>ppmpcs2</dbName>
			<sql>
				<![CDATA[
					select u.user_id, u.cust_text01 from arch_user_ext u
			    ]]>
			</sql>
		</srcInfo>
		<targetInfo>
			<dbName>form</dbName>
			<table>my_test1</table>
			<sql>create index my_test1_idx on my_test1 (user_id)</sql>
		</targetInfo>
	</transferInfo>
	
	<!-- 放在最后执行的sql -->
	<callBackInfo>
		<item>
			<dbName>form</dbName>
			<sql>
				create table my_test2 as select t.account, t.user_name, t1.cust_text01 from my_test t, my_test1 t1 where t.user_id = t1.user_id
			</sql>
			<sql>drop table my_test1 CASCADE</sql>
			<sql>drop table my_test CASCADE</sql>
		</item>
	</callBackInfo>
</root>
